/**
 * Subset of completions for the article motivating examples.
 * Synced from ../../src/cached_data/examples.tsx and novelty_bench.tsx —
 * re-run the Python block in the agent tooling or maintain manually if caches change.
 */
export const GREEK_DEITY_GENERATIONS: string[] = [
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity in Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a well-known deity from Greek mythology.",
    "Zeus is a deity from Greek mythology.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus, the king of the gods and ruler of Mount Olympus.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology.",
    "Zeus is a prominent deity from Greek mythology.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a major deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity in Greek mythology, known as the king of the gods.",
    "Zeus, the king of the gods, is a prominent deity in Greek mythology.",
    "Zeus is a deity from Greek mythology.",
    "Zeus is a prominent deity in Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology.",
    "Zeus is a prominent deity from Greek mythology, often considered the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods.",
    "Zeus is a prominent deity from Greek mythology, known as the king of the gods.",
    "Zeus is a deity from Greek mythology, known as the king of the gods and ruler of Mount Olympus."
  ];

export const BAUDELAIRE_TRANSLATION_GENERATIONS: string[] = [
    "\"In the days when Nature in her powerful exuberance conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful zeal conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful inspiration conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful vigor conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"Back when Nature, in her powerful creativity, conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful rapture conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature, in her powerful inspiration, conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful exuberance conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children each day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood would conceive monstrous children each day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful exuberance conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"When Nature in her powerful verve conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful verve conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful zeal conceived monstrous children each day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity gave birth each day to monstrous children, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful inspiration conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful zeal conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful zeal conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful inspiration conceived monstrous children each day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"When Nature in her powerful mood conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful zeal conceived monstrous children each day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"Back when Nature in her powerful creativity conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful vigor conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful creativity conceived monstrous children each day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live with a young giantess, like a voluptuous cat at the feet of a queen.\"",
    "\"In the days when Nature in her powerful mood conceived monstrous children every day, I would have loved to live beside a young giantess, like a voluptuous cat at the feet of a queen.\""
  ];

export const HAIKU_SNOW_GENERATIONS: string[] = [
    "Silent flakes descend,  \nBlanketing the world in white\u2014  \nWinter's hush revealed.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's breath whispers.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's quiet hush.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's hush revealed.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet breath.",
    "Gentle snowflakes fall,  \nblanketing the silent earth,  \nwinter's quiet hush.",
    "Silent flakes descend,  \nBlanket earth in purest white\u2014  \nWinter whispers hush.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWinter whispers peace.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's breath surrounds.",
    "Whispers of white fall,  \nBlanket earth in quiet grace,  \nWinter's softest touch.",
    "Soft whispers descend,  \nBlanket of white hushes earth\u2014  \nWinter's quiet breath.",
    "Gentle flakes descend,  \nblanketing the silent earth\u2014  \nwinter's quiet breath.",
    "Silent flakes descend,  \nBlanket of white pure and soft,  \nWinter's gentle hush.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's hush revealed.",
    "Silent snowflakes fall,  \nBlanket of white on the earth,  \nWhispers of winter.",
    "Silent snowflakes fall,  \nBlanketing the world in white,  \nWinter's hush descends.",
    "Silent snowflakes fall,  \nBlanketing the world in white,  \nWinter's soft embrace.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWhispers of winter.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet song.",
    "Silent flakes descend,  \nBlanketing the world in white\u2014  \nWinter's gentle hush.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's gentle touch.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's soft embrace.",
    "White flakes gently fall, silent whispers coat the earth, winter's soft embrace.",
    "Silent flakes descend,  \nWhispers blanket the still earth,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's soft embrace.",
    "Silent flakes descend,  \nBlanket of white covers all,  \nWinter whispers peace.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter whispers hush.",
    "Silent snowflakes fall,  \nBlanketing the earth in white,  \nWhispers in the night.",
    "Silent flakes descend,  \nBlanketing the world in white\u2014  \nWinter's hushed embrace.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWinter's soft embrace.",
    "Silent flakes descend, / Blanket earth in purest white, / Winter\u2019s hush begins.",
    "Silent flakes descend,  \nWhispers blanket the still earth,  \nWinter's soft embrace.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWhispers of winter.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet touch.",
    "Silent snowflakes fall,  \nBlanketing the world in white,  \nWhispers of winter.",
    "Silent snowflakes fall,  \nBlanket earth in pure whisper,  \nWinter's gentle hush.",
    "Silent snowflakes fall,  \nBlanket earth in pure white peace,  \nWinter whispers hush.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's hush unfolds.",
    "Silent winter fall,  \nBlanket of white on the ground,  \nWhispers of the cold.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanketing the earth in white\u2014  \nWinter's hush revealed.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWhispers of winter.",
    "Silent flakes descend,  \nBlanketing the world in white,  \nWinter's hush revealed.",
    "Silent snowflakes fall,  \nBlanketing the earth in white,  \nWinter's quiet breath.",
    "Silent flakes descend,  \nBlanket earth in purest white,  \nWinter whispers peace.",
    "Silent snowflakes fall,  \nBlanket earth in purest white,  \nWinter's hush descends.",
    "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's quiet breath."
  ];

export const RANDOM_NUMBERS_GENERATIONS: string[] = [
    "Here are 10 random numbers between 1 and 100: 17, 43, 59, 82, 26, 91, 34, 68, 77, 5.",
    "Here are 10 random numbers between 1 and 100: 27, 84, 6, 59, 33, 72, 15, 48, 91, 64.",
    "Here are 10 random numbers: 7, 34, 56, 89, 23, 78, 12, 45, 67, 91.",
    "Here are 10 random numbers between 1 and 100: 23, 87, 45, 68, 12, 56, 34, 79, 91, 7.",
    "Here are 10 random numbers: 34, 76, 23, 89, 57, 12, 68, 45, 91, 30.",
    "Here are 10 random numbers: 23, 47, 89, 15, 76, 32, 58, 91, 64, 11.",
    "Sure, here are 10 random numbers between 1 and 100: 23, 47, 85, 16, 72, 9, 58, 34, 91, 66.",
    "Here are 10 random numbers between 1 and 100: 23, 87, 5, 42, 76, 19, 58, 34, 91, 68.",
    "Here are 10 random numbers: 23, 67, 45, 89, 12, 34, 76, 55, 91, 38.",
    "Here are 10 random numbers: 23, 47, 89, 15, 62, 38, 74, 5, 96, 51.",
    "Here are 10 random numbers between 1 and 100: 23, 57, 82, 4, 76, 11, 39, 68, 92, 33.",
    "Here are 10 random numbers: 23, 47, 82, 5, 69, 34, 91, 12, 56, 78.",
    "Here are 10 random numbers between 1 and 100: 7, 23, 56, 89, 34, 65, 12, 78, 45, 98.",
    "Here are 10 random numbers between 1 and 100: 7, 23, 56, 89, 15, 42, 78, 34, 61, 94.",
    "Here are 10 random numbers: 23, 57, 89, 6, 42, 78, 34, 61, 15, 99.",
    "Here are 10 random numbers: 7, 34, 56, 82, 19, 45, 67, 23, 89, 10.",
    "Here are 10 random numbers between 1 and 100: 42, 7, 85, 29, 63, 17, 91, 34, 58, 76.",
    "Here are 10 random numbers: 37, 82, 5, 64, 19, 47, 93, 28, 56, 73.",
    "Here are 10 random numbers: 7, 23, 56, 89, 12, 34, 78, 45, 67, 91.",
    "Sure! Here are 10 random numbers: 23, 47, 89, 15, 62, 34, 78, 56, 91, 11.",
    "Here are 10 random numbers between 1 and 100: 17, 53, 89, 24, 67, 42, 76, 33, 58, 91.",
    "Here are 10 random numbers: 34, 76, 59, 22, 81, 47, 5, 68, 93, 12.",
    "Here are 10 random numbers: 42, 87, 15, 63, 29, 76, 54, 9, 33, 91.",
    "Here are 10 random numbers between 1 and 100: 7, 22, 35, 48, 59, 63, 74, 81, 92, 99.",
    "Here are 10 random numbers: 5, 32, 67, 89, 24, 56, 73, 41, 18, 92.",
    "Here are 10 random numbers: 23, 58, 76, 3, 91, 47, 65, 12, 34, 82.",
    "Here are 10 random numbers: 34, 67, 12, 89, 45, 23, 78, 56, 91, 30.",
    "Here are 10 random numbers: 5, 18, 34, 47, 52, 66, 73, 81, 92, 99.",
    "Here are 10 random numbers: 23, 58, 7, 92, 35, 47, 84, 16, 69, 3.",
    "Here are 10 random numbers between 1 and 100: 23, 67, 45, 89, 12, 78, 34, 56, 92, 10.",
    "Here are 10 random numbers between 1 and 100: 23, 87, 45, 62, 19, 78, 34, 56, 91, 12.",
    "Here are 10 random numbers between 1 and 100: 23, 87, 45, 62, 18, 94, 31, 77, 56, 9.",
    "Here are 10 random numbers: 23, 87, 45, 62, 31, 78, 4, 56, 90, 12.",
    "Here are 10 random numbers between 1 and 100: 5, 18, 37, 42, 56, 63, 71, 88, 92, 99.",
    "Sure! Here are 10 random numbers: 23, 67, 81, 45, 10, 94, 38, 52, 76, 29.",
    "Here are 10 random numbers: 23, 76, 5, 89, 34, 58, 92, 17, 41, 63.",
    "Sure! Here are 10 random numbers: 5, 27, 34, 68, 49, 82, 14, 91, 56, 73.",
    "Here are 10 random numbers: 23, 57, 89, 6, 34, 76, 12, 45, 68, 91.",
    "Here are 10 random numbers between 1 and 100: 34, 87, 23, 56, 91, 12, 78, 45, 67, 9.",
    "Here are 10 random numbers between 1 and 100: 27, 45, 68, 12, 99, 34, 57, 76, 81, 23.",
    "Here are 10 random numbers between 1 and 100: 23, 76, 58, 34, 89, 12, 47, 65, 91, 5.",
    "Here are 10 random numbers between 1 and 100: 23, 47, 85, 12, 68, 34, 77, 90, 56, 3.",
    "Here are 10 random numbers: 17, 42, 86, 3, 58, 74, 29, 61, 95, 11.",
    "Here are 10 random numbers between 1 and 100: 47, 82, 15, 63, 29, 77, 4, 91, 36, 58.",
    "Here are 10 random numbers: 42, 87, 16, 59, 73, 24, 68, 91, 33, 5.",
    "Here are 10 random numbers: 23, 87, 45, 12, 56, 78, 34, 91, 67, 10.",
    "Here are 10 random numbers: 7, 34, 89, 56, 22, 73, 48, 15, 62, 91.",
    "Here are 10 random numbers: 45, 22, 87, 13, 59, 76, 34, 68, 91, 5.",
    "Here are 10 random numbers between 1 and 100: 34, 77, 21, 89, 56, 3, 62, 48, 95, 17.",
    "Here are 10 random numbers: 7, 42, 89, 23, 56, 78, 35, 64, 91, 13."
  ];

export const TRUMP_SUMMARY_GENERATIONS: string[] = [
    "Donald Trump's presidency was marked by divisive politics, significant policy changes, and two impeachment trials.",
    "The Trump presidency was characterized by controversial policies, a focus on America First, significant tax reforms, and numerous legal and political challenges.",
    "Donald Trump's presidency was marked by controversial policies, divisive rhetoric, significant deregulation, and major tax reforms, alongside two impeachments and a strong focus on \"America First\" policies.",
    "The Trump presidency was characterized by controversial policies, divisive rhetoric, significant tax reforms, deregulatory efforts, and an impeachment trial, with a focus on \"America First\" policies.",
    "The Trump presidency was marked by divisive politics, significant policy shifts, and an unconventional approach to governance.",
    "Donald Trump's presidency was marked by contentious policies, significant political polarization, and numerous controversies.",
    "The Trump presidency was marked by divisive rhetoric, significant policy shifts, and numerous controversies, both domestically and internationally.",
    "The Trump presidency was marked by controversial policies, polarizing rhetoric, and significant political and social upheaval.",
    "The Trump presidency was marked by significant political polarization, unconventional leadership, and major policy changes in areas such as immigration, taxation, and international relations.",
    "The Trump presidency was marked by significant political polarization, economic growth, contentious immigration policies, and numerous controversies, including two impeachments.",
    "Donald Trump's presidency was marked by controversial policies, significant political polarization, and an emphasis on \"America First\" nationalism.",
    "Donald Trump's presidency was characterized by controversial policies, significant political polarization, and a strong focus on \"America First\" economic and foreign policies.",
    "The Trump presidency was characterized by unconventional leadership, divisive politics, significant policy changes, and controversy.",
    "The Trump presidency was marked by significant political polarization, a focus on America First policies, and numerous controversies and investigations.",
    "The Trump presidency was characterized by controversial policies, a strong focus on immigration and deregulation, significant tax reforms, divisive rhetoric, and two impeachments.",
    "Donald Trump's presidency was marked by controversial policies, divisive rhetoric, economic growth, and significant political polarization.",
    "Donald Trump's presidency was marked by controversial policies, robust economic growth, divisive rhetoric, and two impeachments.",
    "The Trump presidency was marked by a focus on \"America First\" policies, significant political polarization, and numerous controversies and investigations.",
    "The Trump presidency was marked by divisive politics, significant policy changes, and numerous controversies, both domestically and internationally.",
    "The Trump presidency was marked by significant political polarization, economic policies like tax cuts, controversial immigration measures, and two impeachment trials.",
    "The Trump presidency was marked by controversial policies, significant political polarization, a focus on \"America First\" policies, and two impeachments.",
    "The Trump presidency was marked by significant political polarization, controversial policies, and a focus on \"America First\" with notable events like tax reform, trade wars, and two impeachments.",
    "Donald Trump's presidency was characterized by a focus on America First policies, significant tax cuts, controversial immigration policies, and two impeachment trials.",
    "Donald Trump's presidency was marked by controversial policies, strong economic growth, divisive rhetoric, and two impeachments.",
    "Donald Trump's presidency was marked by significant political polarization, controversial policies, and an unconventional approach to leadership and communication.",
    "The Trump presidency was marked by divisive rhetoric, significant policy changes, and controversies, including two impeachments and a focus on \"America First\" policies.",
    "The Trump presidency was marked by contentious policies, a focus on \"America First,\" significant political polarization, and two impeachments.",
    "The Trump presidency was marked by divisive politics, significant policy changes, and controversies, including two impeachments and a focus on \"America First\" policies.",
    "The Trump presidency was characterized by controversial policies, significant political division, and a focus on \"America First\" initiatives.",
    "Donald Trump's presidency was marked by controversial policies, divisive rhetoric, economic growth, and significant political polarization.",
    "The Trump presidency was characterized by controversial policies, significant political polarization, and a focus on America First, with notable events including tax reform, deregulation, and two impeachments.",
    "Donald Trump's presidency was marked by significant political polarization, economic growth, and controversial policies on immigration, trade, and foreign relations.",
    "Donald Trump's presidency was marked by significant political polarization, controversial policies, and a focus on \"America First\" principles.",
    "Donald Trump's presidency was marked by controversial policies, significant political polarization, and major events such as tax reform, trade disputes, and a high-profile response to the COVID-19 pandemic.",
    "Donald Trump's presidency was marked by controversial policies, divisive rhetoric, significant tax reforms, and two impeachments, as well as a focus on deregulation and a strong economy pre-COVID-19.",
    "The Trump presidency was marked by polarizing policies, significant tax reforms, contentious immigration stances, and two impeachment trials.",
    "The Trump presidency was marked by significant political polarization, unconventional governance, economic growth, and contentious policies on immigration, trade, and foreign relations.",
    "Donald Trump's presidency was marked by controversial policies, significant political polarization, a strong focus on immigration and deregulation, and two impeachments.",
    "The Trump presidency was marked by controversial policies, significant political polarization, and an unconventional approach to governance.",
    "The Trump presidency was characterized by a focus on nationalism, significant policy changes, controversial rhetoric, and deep political polarization.",
    "The Trump presidency was marked by significant political polarization, controversial policies, and an unconventional approach to leadership and communication.",
    "The Trump presidency was marked by controversial policies, polarizing rhetoric, and significant impact on domestic and international politics.",
    "The Trump presidency was marked by divisive rhetoric, significant policy changes, economic growth, and numerous controversies, including two impeachments.",
    "The Trump presidency was marked by controversial policies, divisive rhetoric, economic growth, and significant political polarization.",
    "Donald Trump's presidency was marked by significant political polarization, controversial policies, and a focus on \"America First\" economic and immigration strategies.",
    "Donald Trump's presidency was marked by significant political polarization, economic growth, controversial policies, and two impeachments.",
    "The Trump presidency was marked by controversial policies, divisive rhetoric, significant economic changes, and challenges such as the COVID-19 pandemic.",
    "Donald Trump's presidency was marked by significant political polarization, economic changes, and controversial policies on immigration and trade.",
    "The Trump presidency was marked by contentious politics, significant policy shifts, and a deeply polarized national atmosphere.",
    "The Trump presidency was marked by controversial policies, a focus on nationalism and deregulation, significant tax cuts, impeachment proceedings, and a deeply polarized political climate."
  ];

export const OBAMA_SUMMARY_GENERATIONS: string[] = [
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, along with challenges like partisan gridlock and economic recovery from the 2008 financial crisis.",
    "Barack Obama's presidency focused on healthcare reform, economic recovery, and progressive social policies while facing significant political polarization.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts following the Great Recession, and the operation that killed Osama bin Laden, alongside challenges like partisan gridlock and racial tensions.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like political polarization and debates over foreign policy.",
    "Barack Obama's presidency focused on healthcare reform, economic recovery, and social progress, including passing the Affordable Care Act, navigating the aftermath of the Great Recession, and supporting marriage equality.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and the Paris Climate Agreement, alongside challenges like partisan gridlock and global economic recovery.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, economic recovery efforts following the Great Recession, and significant foreign policy achievements such as the killing of Osama bin Laden and the Iran nuclear deal.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and climate change initiatives, as well as challenges like partisan gridlock and foreign policy complexities.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, amidst challenges like political polarization and debates over foreign policy.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the economic recovery following the 2008 financial crisis, and the killing of Osama bin Laden, alongside challenges like political polarization and struggles with healthcare rollout.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, the killing of Osama bin Laden, and landmark legislation on climate change and social issues, alongside challenges like political polarization and foreign policy complexities.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by significant achievements such as the Affordable Care Act and the killing of Osama bin Laden, amidst challenges like the Great Recession and partisan divisions.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, while also facing challenges like political polarization and economic recovery.",
    "The Obama presidency was marked by significant healthcare reform, the killing of Osama bin Laden, economic recovery efforts after the Great Recession, and a focus on climate change and social issues.",
    "Barack Obama's presidency is marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and navigating the country through the economic recovery, alongside challenges like political polarization and limited progress on climate change and immigration reform.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, a focus on economic recovery following the 2008 financial crisis, and significant policy changes in areas such as healthcare, climate change, and foreign policy.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by the passage of the Affordable Care Act, economic recovery efforts, the killing of Osama bin Laden, and significant advancements in climate and social policies.",
    "The Obama presidency was marked by significant economic recovery efforts, the passage of the Affordable Care Act, and notable foreign policy achievements like the killing of Osama bin Laden.",
    "Barack Obama's presidency was marked by significant achievements like the Affordable Care Act, the killing of Osama bin Laden, and the Paris Climate Agreement, alongside challenges such as economic recovery and partisan divides.",
    "Barack Obama's presidency was marked by significant achievements including the Affordable Care Act, economic recovery efforts, and landmark foreign policy decisions, amidst challenges like political polarization.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, while facing significant political polarization.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by significant achievements like the Affordable Care Act, the killing of Osama bin Laden, and efforts to recover from the Great Recession, alongside challenges such as political polarization and foreign policy complexities.",
    "Barack Obama's presidency (2009-2017) was marked by significant legislative achievements like the Affordable Care Act, a focus on economic recovery, and notable foreign policy efforts including the killing of Osama bin Laden.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, alongside challenges like partisan gridlock and economic recovery.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like partisan gridlock and foreign policy complexities.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, the economic recovery from the Great Recession, and the operation that killed Osama bin Laden.",
    "Barack Obama's presidency focused on healthcare reform, economic recovery, and social issues, including increased attention to climate change and foreign diplomacy.",
    "The Obama presidency, from 2009 to 2017, was marked by significant legislative achievements like the Affordable Care Act, efforts to revive the economy post-recession, and a focus on progressive social policies.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and the Paris Climate Agreement, alongside challenges like partisan gridlock and economic recovery efforts.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and foreign policy initiatives like the Iran nuclear deal, alongside challenges including partisan divisions and global conflicts.",
    "Barack Obama's presidency focused on healthcare reform, economic recovery, and social issues, including the Affordable Care Act and the legalization of same-sex marriage.",
    "Barack Obama's presidency was marked by significant achievements including the Affordable Care Act, economic recovery efforts, and advancements in social issues, alongside challenges like political polarization and international conflicts.",
    "The Obama presidency was marked by significant health care reform, the killing of Osama bin Laden, and efforts to recover from the Great Recession.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, amidst challenges including economic recovery and political polarization.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, efforts to recover from the Great Recession, and advancements in environmental and social policies.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and initiatives on climate change, alongside challenges like economic recovery and partisan divisions.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and the response to the 2008 financial crisis, alongside challenges like political polarization and foreign policy complexities.",
    "Barack Obama's presidency was marked by significant health care reform, economic recovery efforts, and advancements in social issues, including marriage equality.",
    "Barack Obama's presidency focused on healthcare reform, economic recovery, and progressive social policies, while facing significant partisan opposition.",
    "Barack Obama's presidency was marked by significant legislative achievements such as the Affordable Care Act, economic recovery efforts, and initiatives in foreign policy, while facing challenges from a divided Congress.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like partisan gridlock and foreign policy complexities.",
    "Barack Obama's presidency was marked by landmark healthcare reform, the killing of Osama bin Laden, economic recovery efforts, and significant advancements in civil rights.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, the killing of Osama bin Laden, and progressive social policies, amidst challenges like political polarization and foreign policy complexities.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts after the Great Recession, and the operation that killed Osama bin Laden, alongside challenges like partisan gridlock and debates over foreign and domestic policy.",
    "Barack Obama's presidency, from 2009 to 2017, was marked by significant achievements such as the Affordable Care Act, the economic recovery following the Great Recession, and a focus on climate change and foreign diplomacy, alongside challenges such as political polarization and racial tensions.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, alongside challenges like economic recovery and political polarization.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the economic recovery following the Great Recession, and the operation that killed Osama bin Laden, alongside challenges like political polarization and debates over foreign and domestic policies.",
    "Barack Obama's presidency was marked by the passage of the Affordable Care Act, the killing of Osama bin Laden, economic recovery efforts, and significant strides in environmental and social policies.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like partisan division and foreign policy complexities.",
    "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to combat climate change, alongside challenges including economic recovery and partisan gridlock."
  ];
