#!/usr/bin/env node
/**
 * Flattens nested ATEPP transcripts for the viewer (two shapes):
 *
 * 1) examplesAteppByPiece — keys are piece ids only (e.g. atepp__Bach_542).
 *    Values: all transcript strings for that piece (every performer / video),
 *    each truncated to maxLineLen.
 *
 * 2) examplesAteppByPiecePerformer — keys are "<pieceId> <performer>".
 *    Values: transcript strings for that performer on that piece only.
 *
 * Writes src/cached_data/examples_atepp.tsx (committed). Does not write .json.
 *
 * Usage:
 *   node scripts/build_atepp_examples.mjs [source.json] [limit] [maxLineLen]
 * Defaults: limit 10, maxLineLen 500
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");

const defaultSource = path.join(
  process.env.HOME || "",
  "Downloads/transcripts_per_piece_per_performer/transcripts_three_tier_atepp_2026-04-01_2239.json"
);

const srcPath = process.argv[2] || process.env.ATEPP_SOURCE || defaultSource;
const limit = parseInt(process.argv[3] || process.env.ATEPP_LIMIT || "10", 10);
const maxLineLen = parseInt(
  process.argv[4] || process.env.ATEPP_MAX_LINE_LEN || "500",
  10
);

if (!fs.existsSync(srcPath)) {
  console.error("Source file not found:", srcPath);
  process.exit(1);
}

function truncate(s) {
  let line = String(s);
  if (line.length > maxLineLen) line = line.slice(0, maxLineLen);
  return line;
}

const raw = JSON.parse(fs.readFileSync(srcPath, "utf8"));
const pieceKeys = Object.keys(raw).slice(0, limit);
const byPiece = {};
const byPiecePerformer = {};

for (const pieceKey of pieceKeys) {
  const performers = raw[pieceKey];
  const pieceOutputs = [];
  for (const [performerName, videos] of Object.entries(performers)) {
    const promptKey = `${pieceKey} ${performerName}`;
    const outputs = [];
    for (const transcript of Object.values(videos)) {
      const line = truncate(transcript);
      outputs.push(line);
      pieceOutputs.push(line);
    }
    byPiecePerformer[promptKey] = outputs;
  }
  byPiece[pieceKey] = pieceOutputs;
}

const destPath = path.join(repoRoot, "src/cached_data/examples_atepp.tsx");
const body = `/** Auto-generated by scripts/build_atepp_examples.mjs — do not edit by hand. */
export const examplesAteppByPiece: { [key: string]: string[] } = ${JSON.stringify(
  byPiece,
  null,
  2
)};

export const examplesAteppByPiecePerformer: { [key: string]: string[] } = ${JSON.stringify(
  byPiecePerformer,
  null,
  2
)};
`;
fs.mkdirSync(path.dirname(destPath), { recursive: true });
fs.writeFileSync(destPath, body);
const stat = fs.statSync(destPath);
console.log(
  "Wrote",
  destPath,
  "(" +
    Object.keys(byPiece).length +
    " pieces, " +
    Object.keys(byPiecePerformer).length +
    " piece+performer prompts,",
  Math.round(stat.size / 1024),
  "KB)"
);
