export const examples: { [key: string]: string[]; } = {'Write me a haiku about snow': ["Silent flakes descend,  \nBlanketing the world in white,  \nWinter's soft embrace.",
  'Silent flakes descend,  \nblanketing the world in white—  \nwinter whispers soft.',
  "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's soft embrace.",
  "Snowflakes gently fall,  \nWhispers of a winter's chill,  \nBlanket earth in white.",
  'Silent white blankets, / Covering the earth softly, / Winter whispers hush.',
  "Silent flakes descend,  \nBlanket earth in purest white,  \nWinter's quiet breath.",
  "Silent flakes descend,  \nBlanketing the earth in white,  \nWinter's hush revealed.",
  "Silent flakes descend,  \nBlanket earth in purest white—  \nWinter's quiet breath.",
  "Silent flakes descend,  \nWhispers on a winter's breeze,  \nBlanket earth in white.",
  "Silent flakes descend,  \nblanketing the earth in white—  \nwinter's hushed embrace."],
 'Write me a haiku about visualization': ['Colors dance on charts,  \nData whispers through patterns,  \nTruth in lines revealed.',
  "Colors and shapes blend,  \nData's story comes to life,  \nClarity unfolds.",
  "Colors paint the mind,  \nData's story comes to life,  \nTruth in shapes and lines.",
  "Colors and patterns,  \nData's story comes to life—  \nInsights in plain sight.",
  'Colors intertwine,  \nPatterns emerge from the mist—  \nData comes to life.',
  'Data comes alive,  \nCharts and graphs tell vivid tales,  \nClarity unfolds.',
  "Colors weave through graphs,  \nData's story comes to life—  \nInsight in each line.",
  'Data comes alive,  \nColors and shapes tell the tale—  \nClarity revealed.',
  "Colors and patterns,  \nData's story comes alive,  \nTruth in clear design.",
  "Colors and shapes dance,  \nData's story comes alive,  \nTruth in graphs revealed."],
 'Write an alternate first line of A Tale Of Two Cities': ['It was a time of stark contrasts, with moments of brilliance and shadows of despair.',
  'It was a time of contrasts, when hope and despair walked hand in hand.',
  'It was a time of stark contrasts, an age of upheaval and hope.',
  'It was an era of extremes, where prosperity met poverty head-on.',
  'It was the dawn of a new era, filled with both hope and despair.',
  'It was an era of contrasts, where light and shadow intertwined in the lives of many.',
  '"It was an age of contradictions and complexities, where hope and despair walked hand in hand."',
  'It was an age of stark contrasts, where hope and despair danced hand in hand.',
  'It was the era of contradictions, where the light of hope flickered alongside shadows of despair.',
  '"It was a time of contrasts and contradictions, a world caught between light and shadow."'],
 'What is the first line of A Tale Of Two Cities?': ['"It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness,..."',
  'The first line of "A Tale of Two Cities" is: "It was the best of times, it was the worst of times..."',
  '"It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only."',
  'The first line is "It was the best of times, it was the worst of times."',
  'The first line of "A Tale of Two Cities" is: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..."',
  'The first line is "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only."',
  'The first line is: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..."',
  'The first line is "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..."',
  'The first line is: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness..."',
  'The first line is "It was the best of times, it was the worst of times..."'],
 'Who is Jeff Heer?': ['Jeff Heer is a computer science professor known for his work in data visualization and his contributions to tools like D3.js and Vega.',
  'Jeff Heer is a computer scientist known for his work in data visualization and as a professor at the University of Washington.',
  'Jeff Heer is a computer science professor known for his work in data visualization and human-computer interaction.',
  'Jeff Heer is a computer scientist known for his work in data visualization and is a professor at the University of Washington.',
  'Jeff Heer is a computer scientist known for his work in data visualization and as a professor at the University of Washington.',
  'Jeff Heer is a professor of computer science at the University of Washington, known for his work in data visualization.',
  'Jeff Heer is a computer science professor known for his work in data visualization and the development of visualization tools like D3.js and Vega.',
  'Jeff Heer is a computer scientist known for his work in data visualization and as a professor at the University of Washington.',
  'Jeff Heer is a computer scientist known for his work in data visualization and as a professor at the University of Washington.',
  'Jeff Heer is a computer scientist known for his work in data visualization and as a professor at the University of Washington.'],
 'Summarize the Trump presidency in one sentence': ['The Trump presidency was marked by a focus on America First policies, significant deregulation, contentious immigration reforms, and polarizing rhetoric, culminating in an impeachment and a controversial response to the COVID-19 pandemic.',
  'The Trump presidency was marked by divisive politics, significant policy changes, and widespread controversy.',
  'Donald Trump\'s presidency was marked by controversial policies, significant deregulation, two impeachments, and a focus on "America First" principles.',
  'The Trump presidency was marked by controversial policies, significant political polarization, and a focus on America First principles.',
  'The Trump presidency was marked by divisive politics, significant policy changes, and a focus on America First, alongside numerous controversies and impeachment proceedings.',
  'The Trump presidency was characterized by controversial policies, significant political polarization, and an unconventional style of governance.',
  'Donald Trump\'s presidency was marked by controversial policies, significant political polarization, and a focus on "America First" in both domestic and foreign affairs.',
  'The Trump presidency was marked by significant political polarization, economic growth, controversial policies, and an unorthodox approach to governance.',
  'The Trump presidency was marked by unconventional leadership, significant policy changes, and deep political polarization.',
  "Donald Trump's presidency was characterized by significant political polarization, unconventional leadership style, and major policy changes in areas such as trade, immigration, and foreign relations."],
 'Summarize the Obama presidency in one sentence': ["Barack Obama's presidency was marked by significant healthcare reform, economic recovery efforts, and advancements in social issues, alongside challenges in foreign policy and political polarization.",
  "Barack Obama's presidency was marked by the passage of the Affordable Care Act, the operation that led to the death of Osama bin Laden, and efforts to recover from the Great Recession.",
  "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like partisan gridlock and foreign policy complexities.",
  "Barack Obama's presidency focused on healthcare reform, economic recovery, and foreign policy initiatives, including the Affordable Care Act and the killing of Osama bin Laden.",
  "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the killing of Osama bin Laden, alongside challenges like partisan gridlock and foreign policy complexities.",
  "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts toward economic recovery, amidst challenges like partisan divisions and international conflicts.",
  "Barack Obama's presidency was marked by significant achievements including the Affordable Care Act, the killing of Osama bin Laden, and the legalization of same-sex marriage, amid challenges such as the economic recovery and partisan divisions.",
  'The Obama presidency was marked by significant achievements such as the Affordable Care Act, the killing of Osama bin Laden, and efforts to recover from the Great Recession, alongside challenges like partisan gridlock and foreign policy complexities.',
  "Barack Obama's presidency was marked by significant achievements such as the Affordable Care Act, economic recovery efforts, and the legalization of same-sex marriage, alongside challenges like partisan gridlock and ongoing international conflicts.",
  "Barack Obama's presidency, from 2009 to 2017, was marked by healthcare reform, economic recovery efforts, and significant foreign policy initiatives, including the killing of Osama bin Laden."],
 'What is your name?': ['I am an AI language model created by OpenAI, often referred to as ChatGPT.',
  'I am called Assistant.',
  "I am an AI assistant and don't have a personal name, but you can call me Assistant.",
  'I am called Assistant.',
  'I am called Assistant.',
  'I am an AI assistant and do not have a personal name, but you can call me Assistant.',
  'I am an AI assistant and do not have a personal name, but you can call me Assistant.',
  'I am an AI language model created by OpenAI, often referred to as ChatGPT.',
  'I am an AI and do not have a personal name, but you can call me Assistant.',
  'I am called Assistant.'],
 'Summarize the wikipedia article on OpenAI in one sentence': ['OpenAI is an artificial intelligence research laboratory consisting of the non-profit OpenAI Inc. and its for-profit subsidiary OpenAI LP, focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research lab consisting of the non-profit OpenAI Inc. and its for-profit subsidiary OpenAI LP, focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI, known for creating advanced AI models like GPT and DALL-E.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is a research organization focused on developing and promoting friendly artificial intelligence for the benefit of humanity.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research organization focused on developing and promoting friendly AI for the benefit of humanity.',
  'OpenAI is an artificial intelligence research lab known for developing advanced AI technologies, including the GPT series of language models, with the mission to ensure that AI benefits all of humanity.']}